{"name": "test_vwo_login_negative", "status": "broken", "statusDetails": {"message": "RecursionError: maximum recursion depth exceeded", "trace": "setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"2ddaec19e02abfdaf4d9e6b17abe0af0\")>\n\n    @allure.epic(\"vwo Login test\")\n    @allure.feature(\"TC01 vwo App negative test\")\n    # @pytest.mark.negative\n    def test_vwo_login_negative(setup):\n        driver=setup\n        login_page=LoginPage(driver)\n        login_page.Login_to_vwo(usr=\"admin@gmail.com\",pwd=\"admin\")\n        time.sleep(5)\n>       error_message=login_page.get_error_msg_text()\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\ntests\\VWOLogintest\\test_vwo_login.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests\\Pageobjects\\LoginPage.py:41: in get_error_msg_text\n    return self.get_error_msg_text().text\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\ntests\\Pageobjects\\LoginPage.py:41: in get_error_msg_text\n    return self.get_error_msg_text().text\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\nE   RecursionError: maximum recursion depth exceeded\n!!! Recursion detected (same locals & position)"}, "start": 1752348482179, "stop": 1752348491593, "uuid": "1272fc26-04dc-4751-978f-0b6017f44a6f", "historyId": "efc6822957c2f7073ee16577998408d9", "testCaseId": "efc6822957c2f7073ee16577998408d9", "fullName": "tests.VWOLogintest.test_vwo_login#test_vwo_login_negative", "labels": [{"name": "feature", "value": "TC01 vwo App negative test"}, {"name": "epic", "value": "vwo Login test"}, {"name": "parentSuite", "value": "tests.VWOLogintest"}, {"name": "suite", "value": "test_vwo_login"}, {"name": "host", "value": "DESKTOP-F5PR8ID"}, {"name": "thread", "value": "340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.VWOLogintest.test_vwo_login"}]}